version: 27.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 1
before_build:
- cmd: nuget restore
build:
  project: srcrepair.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: 7z a snapshot_%APPVEYOR_REPO_COMMIT:~0,7%.7z %APPVEYOR_BUILD_FOLDER%\srcrepair\bin\$(configuration)
test: off
artifacts:
- path: snapshot_*.7z
  name: snapshot
