version: 27.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
clone_depth: 1
before_build:
- cmd: nuget restore
build:
  project: srcrepair.sln
  verbosity: normal
test: off
